// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcszNfeZHJLBE3ZlUi3ENE-MYDgf78BqE',
    appId: '1:318466298963:web:680615fc59883675a1a2a6',
    messagingSenderId: '318466298963',
    projectId: 'chat-app-a08c6',
    authDomain: 'chat-app-a08c6.firebaseapp.com',
    storageBucket: 'chat-app-a08c6.firebasestorage.app',
    measurementId: 'G-8ELSQLCZPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8hVNYaXsPXB-MoBhUfRTfnnGN18I-g2c',
    appId: '1:318466298963:android:aa6b56c08eb07459a1a2a6',
    messagingSenderId: '318466298963',
    projectId: 'chat-app-a08c6',
    storageBucket: 'chat-app-a08c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuUe4QFuIWRVRUYUw1QrMfeTwkHpDocfM',
    appId: '1:318466298963:ios:ee1ece950c90b02ca1a2a6',
    messagingSenderId: '318466298963',
    projectId: 'chat-app-a08c6',
    storageBucket: 'chat-app-a08c6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuUe4QFuIWRVRUYUw1QrMfeTwkHpDocfM',
    appId: '1:318466298963:ios:ee1ece950c90b02ca1a2a6',
    messagingSenderId: '318466298963',
    projectId: 'chat-app-a08c6',
    storageBucket: 'chat-app-a08c6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcszNfeZHJLBE3ZlUi3ENE-MYDgf78BqE',
    appId: '1:318466298963:web:f2d491a9231ea78da1a2a6',
    messagingSenderId: '318466298963',
    projectId: 'chat-app-a08c6',
    authDomain: 'chat-app-a08c6.firebaseapp.com',
    storageBucket: 'chat-app-a08c6.firebasestorage.app',
    measurementId: 'G-2XBDQFMF24',
  );
}
